# Generated by Django 6.0.2 on 2026-02-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominee',
            name='secondary_text',
            field=models.CharField(blank=True, help_text='Extra info like Song Name or Character Name', max_length=255, null=True),
        ),
    ]
